[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "IntersectionZoo"
authors = [{name = "Vindula Jayawardana", email = "vindula@mit.edu"}]
dynamic = ["version", "description"]
